#!/usr/bin/env python3
"""Embed the three small region maps so the editor works from file:// URLs."""

from __future__ import annotations

import base64
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent
SOURCES = {
    "Brandenburg": {
        "map": "assets/regions/Brandenburg/region-map.png",
    },
    "Sacre": {
        "map": "assets/regions/Sacre/region-map.png",
    },
    "Trevi": {
        "map": "assets/regions/Trevi/region-map.png",
    },
}


def data_url(relative_path: str) -> str:
    encoded = base64.b64encode((ROOT / relative_path).read_bytes()).decode("ascii")
    return f"data:image/png;base64,{encoded}"


def main() -> None:
    assets = {
        scene: {kind: data_url(path) for kind, path in files.items()}
        for scene, files in SOURCES.items()
    }
    payload = json.dumps(assets, separators=(",", ":"))
    output = ROOT / "embedded-editor-assets.js"
    output.write_text(
        "// Generated by generate_embedded_editor_assets.py; supports file:// Canvas use.\n"
        f"window.PSUGSEditorAssets={payload};\n",
        encoding="utf-8",
    )
    print(f"Wrote {output.name} ({output.stat().st_size / 1024 / 1024:.2f} MiB)")


if __name__ == "__main__":
    main()
